[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "brain-age-federated"
version = "1.0.0"
description = "Federated and centralized training workflows for brain age estimation"
dependencies = [
    "flwr>=1.33.0",
    "flwr-datasets[vision]",
    "monai",
    "torch",
    "torchvision",
    "scikit-learn",
    "nibabel",
    "tqdm",
    "pandas",
    "scipy",
    "matplotlib",
    "numpy"
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.flwr.app]
publisher = "alvieupnext"

[tool.flwr.app.components]
serverapp = "src.server_app:app"
clientapp = "src.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 5
nodes = 3
kcrossval = 10
split = "distribution"
distribution = "Gaussian"
strategy = "FedAvg"
alias = "3_Node"
save-dir = "./utils/models/"
epochs = 20
patience = 4
seed = ""
mock = false
